name: Node.js CI
on: [push]
jobs:

  plan:
    runs-on: ubuntu-latest
    outputs:
      matrix: "[]"

  apply:
    needs: [ plan ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - name: "test 1"
           prop1: "this is a test"
         - name: "test 2"
           prop1: "this is another test"
    steps:
      - name: Echo site details
        env:
          NAME: ${{ matrix.name }}
          PROP1: ${{ matrix.prop1 }}
        run: echo $NAME $PROP1
