name: test
on:
  push:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - run: whoami

      - uses: actions/checkout@v2

      - uses: actions/checkout@v2

      - uses: docker://ubuntu:latest
        with:
          args: touch test.txt

      - run: ls -la

      - uses: actions/checkout@v2

      - run: ls -la
