name: Node.js CI
on: [push]
jobs:

  plan:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
    outputs:
      matrix: "[]"

  apply:
    needs: [ plan ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include: ${{ fromJson(needs.plan.outputs.matrix) }}
    steps:
      - name: Echo site details
        env:
          NAME: ${{ matrix.name }}
          PROP1: ${{ matrix.prop1 }}
        run: echo $NAME $PROP1
